<Splash>:
    Label:
        canvas.before:
            Color:
                rgba: .258, .529, .960, 1
            Rectangle:
                pos: self.pos
                size: self.size 
        text: 'Relatório de Serviço'
        text_size: self.width, None
        size: self.texture_size
        valign: 'middle'
        halign: 'center'
        color: (1, 1, 1, 1)         
        font_size: '50sp'